version: '3.8'
services:
  app:
    build: ./app
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - app-connect

  # server:
  #   build: ./server
  #   restart: always
  #   depends_on:
  #     - mongo
  #   environment:
  #     PORT: 5000
  #     MONGO_URI: mongodb://localhost/vitrinerapida
  #     MONGO_USER: root
  #     MONGO_PASS: 123
  #     JWT_SECRET: p1Nc9NnWrALjKKHtJZ1HQLIgrAwxL8py
  #     JWT_EXPIRATION: 24h
  #     SALT_ROUNDS: 6
  #     ADMIN_PASS: imtheguy
  #   ports:
  #     - 7000:7000
  #   networks:
  #     - app-connect
      
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rWBNkToeQzlClWupM9kt
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - /root/projects/vitrinerapida/backups:/backups
    networks:
      - app-connect

volumes:
  db-data:

networks:
  app-connect:
      driver: bridge